name: CDK Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt

      - name: Run pytest
        run: |
          pytest tests/

  deploy-dev:
    environment: dev
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Configure AWS Credentials for Development
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: eu-north-1

      - name: Install cdk
        run: npm install -g aws-cdk

      - name: CDK Bootstrap for Development
        run: |
          cdk bootstrap

      - name: CDK Deploy to Development
        run: |
          cdk deploy --require-approval never

  deploy-prod:
    environment: prod
    needs: deploy-dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Configure AWS Credentials for Production
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: eu-north-1

      - name: Install cdk
        run: npm install -g aws-cdk

      - name: CDK Bootstrap for Production
        run: |
          cdk bootstrap

      - name: CDK Deploy to Production
        run: |
          cdk deploy --require-approval never
